server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/restaurantdb
  application:
    name: restaurant-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost